name: CI

on:
  push:
    branches:
      - master
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint

  tests:
    name: "Tests on Node.js ${{ matrix.node-version }} - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ["18", "20", "22"]
        os:
          - 'ubuntu-latest'
          - 'windows-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: git fetch --all && git fetch --unshallow # this is to work for the acceptance tests
      - run: pnpm test
        env:
          GITHUB_API_URL: ""
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }} #this is for acceptance tests
